name: PEP8 Validation

on:
  push:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          pip install pylint pandas openpyxl

      - name: Run Validation
        run: |
          python generate_report.py

      - name: Read Report Name
        run: |
          echo "REPORT_FILE=$(cat report_name.txt)" >> $GITHUB_ENV

      - name: Upload Excel Report
        uses: actions/upload-artifact@v4
        with:
          name: PEP8_Reports
          path: ${{ env.REPORT_FILE }}
